### ISSUE TITLE
Project2 - Basic Pathfinding

### ISSUE THREAD

**Issue by kenny-designs** [kenny-designs/Robot-Projects#13]

**Comment by kenny-designs** [comment]
Ran a few tests on the robot. It appears that it doesn't initially know it's position between runs with the odometer. Only after it has ran for a moment does it semi-accurately know where it's located. I'm testing to see if I can address this problem.

**Comment by kenny-designs** [comment]
I'm not exactly sure why but we must falsely invoked Read() then SetSpeed() for the robot's location to be revealed correctly on the first go.

`robot.Read();`
`pp.SetSpeed(0, 0);`

**Comment by kenny-designs** [comment]
Managed to greatly simplify the code for determining which direction the robot should turn. I did this by hand writing a table representing all the possible combinations of positive/negative dir.x, dir.y, wpNorm.x, and wpNorm.y. I noted the direction the robot should turn for each combination and managed to come up with a simplified solution.

For comparison, we went from:
```
if (((dir.x > 0 && wpNorm.x > 0) && dir.y > wpNorm.y) ||
    ((dir.x < 0 && wpNorm.x < 0) && dir.y < wpNorm.y) ||
    ((dir.y > 0 && wpNorm.y > 0) && dir.x < wpNorm.x) ||
    ((dir.y < 0 && wpNorm.y < 0) && dir.x > wpNorm.x) ||
     (dir.x > 0 && dir.y > 0 && wpNorm.x < 0 && wpNorm.y < 0) ||
     (dir.x > 0 && dir.y < 0 && wpNorm.x < 0 && wpNorm.y > 0))
{
  angle *= -1;
}
```

to:
```
if ((dir.x > 0 != wpNorm.y > 0) &&
      !(dir.x < 0 && dir.y < 0 && wpNorm.x > 0 && wpNorm.y > 0))
  {
    angle *= -1;
  }
```

**Comment by mattlol85** [comment]
Testing coords (1,5) to (3,5) moves improperly.

The first coord works fine, the second fails.

**Comment by kenny-designs** [comment]
> Testing coords (1,5) to (3,5) moves improperly.
> 
> The first coord works fine, the second fails.

Thank you good sir I shall fix this!
