### ISSUE TITLE
proj6 - star

### ISSUE THREAD

**Issue by kenny-designs** [kenny-designs/Robot-Projects#73]
Implement the A* algo. @saheedandrew shall be taking the lead :sunglasses:. Don't forget, you can do this all in Java (also don't forget to make a branch called whatever you'd like)! In a pinch, we can also implement the wavefront algo which is supposedly easier to do.

Be sure to put all relevant work in the project6 directory by the way!

**Comment by saheedandrew** [comment]
gonna start working on this on friday @kenny-designs

**Comment by kenny-designs** [comment]
:sun_with_face:
